version: "3.8"
services:
  mongodb:
    image: 'mongo'
  backend:
    build: ./Tasky-backend
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
  frontend:
    build: ./Tasky-frontend
    ports: 
      - '3000:3000'
    stdin_open: true
    tty: true
    depends_on: 
      - backend

volumes: 
  data:
  logs:
